@echo off
REM Retardio Easy Setup Script - Windows Version
REM This script automatically configures your node and connects to the network

setlocal EnableDelayedExpansion

REM Configuration
set SCRIPT_DIR=%~dp0
set BUILD_DIR=%SCRIPT_DIR%build
set RETARDIOD=%BUILD_DIR%\bin\retardiod.exe
set RETARDIO_CLI=%BUILD_DIR%\bin\retardio-cli.exe
set DATADIR=%USERPROFILE%\.retardio
set CONF_FILE=%DATADIR%\retardio.conf

REM Banner
cls
echo.
echo ================================================
echo.
echo       RETARDIO EASY SETUP WIZARD
echo.
echo   This will automatically:
echo   * Check if rebuild is needed
echo   * Configure your node
echo   * Connect to peer nodes
echo   * Start your node
echo.
echo ================================================
echo.
echo.

REM Step 1: Check environment
echo [Step 1] Checking environment...
if not exist "%SCRIPT_DIR%src" (
    echo Error: Please run this script from the retardio-coin directory!
    pause
    exit /b 1
)
echo OK: Environment check passed
echo.

REM Step 2: Check if binaries exist
echo [Step 2] Checking if build is needed...
set NEEDS_REBUILD=0

if not exist "%RETARDIOD%" (
    echo WARNING: retardiod.exe not found
    set NEEDS_REBUILD=1
) else if not exist "%RETARDIO_CLI%" (
    echo WARNING: retardio-cli.exe not found
    set NEEDS_REBUILD=1
) else (
    echo OK: Binaries found
)

if !NEEDS_REBUILD! equ 1 (
    echo.
    echo ================================================
    echo   BUILD REQUIRED
    echo ================================================
    echo.
    echo Your node needs to be built. Please use one of these methods:
    echo.
    echo Option 1: Build with WSL (Recommended)
    echo   wsl bash -c "cd /mnt/c/Users/%USERNAME%/retardio-coin/build && make -j$(nproc)"
    echo.
    echo Option 2: Build with Visual Studio
    echo   Open retardio-coin.sln in Visual Studio and build
    echo.
    echo Option 3: Build with CMake
    echo   cd build
    echo   cmake --build . -j
    echo.
    echo After building, run this script again.
    echo.
    pause
    exit /b 1
)
echo.

REM Step 3: Create data directory
echo [Step 3] Setting up data directory...
if not exist "%DATADIR%" (
    mkdir "%DATADIR%"
    echo Created: %DATADIR%
) else (
    echo OK: Data directory exists
)
echo.

REM Step 4: Configure retardio.conf
echo [Step 4] Configuring retardio.conf...

if exist "%CONF_FILE%" (
    echo WARNING: Configuration file already exists
    echo   Location: %CONF_FILE%
    echo.
    set /p "OVERWRITE=Overwrite it? (y/N): "
    if /i not "!OVERWRITE!"=="y" (
        echo Keeping existing configuration
        goto :skip_config
    )
    del "%CONF_FILE%"
    echo Removed old configuration
)

echo Creating new configuration file...

REM Generate random password (simple version for Windows)
set RPC_PASSWORD=%RANDOM%%RANDOM%%RANDOM%%RANDOM%

(
echo # Retardio Node Configuration
echo # Auto-generated by easy_setup.bat on %DATE% %TIME%
echo.
echo # Network Settings
echo server=1
echo listen=1
echo port=18333
echo maxconnections=125
echo.
echo # RPC Settings
echo rpcport=18332
echo rpcuser=retardiouser
echo rpcpassword=!RPC_PASSWORD!
echo rpcbind=127.0.0.1
echo rpcallowip=127.0.0.1
echo.
echo # Performance
echo dbcache=450
echo maxmempool=300
echo.
echo # Indexing
echo txindex=1
echo.
echo # Logging
echo debug=0
echo.
echo # Peer nodes ^(will be added below^)
) > "%CONF_FILE%"

echo OK: Configuration file created
echo   RPC Password: !RPC_PASSWORD!
echo   Saved to: %CONF_FILE%

:skip_config
echo.

REM Step 5: Add peer nodes
echo [Step 5] Configure peer nodes...
echo.
echo To connect to the Retardio network, you need to add at least one peer node.
echo.
set /p "ADD_PEER=Do you have a peer node IP address to add? (y/N): "

if /i "!ADD_PEER!"=="y" (
    :peer_loop
    set /p "PEER_IP=Enter peer IP address (or 'done' to finish): "

    if "!PEER_IP!"=="done" goto :peer_done

    set /p "PEER_PORT=Enter peer port (default 18333): "
    if "!PEER_PORT!"=="" set PEER_PORT=18333

    echo addnode=!PEER_IP!:!PEER_PORT! >> "%CONF_FILE%"
    echo OK: Added peer: !PEER_IP!:!PEER_PORT!

    set /p "ADD_MORE=Add another peer? (y/N): "
    if /i "!ADD_MORE!"=="y" goto :peer_loop

    :peer_done
) else (
    echo WARNING: No peers added
    echo You can add them later by editing: %CONF_FILE%
    echo Add lines like: addnode=192.168.1.100:18333
)
echo.

REM Step 6: Firewall
echo [Step 6] Firewall configuration...
echo.
echo Port 18333 must be open for incoming connections.
echo.
set /p "OPEN_FIREWALL=Open port 18333 in Windows Firewall? (y/N): "

if /i "!OPEN_FIREWALL!"=="y" (
    netsh advfirewall firewall add rule name="Retardio P2P" dir=in action=allow protocol=TCP localport=18333 >nul 2>&1
    if !errorlevel! equ 0 (
        echo OK: Port 18333 allowed in Windows Firewall
    ) else (
        echo WARNING: Failed to add firewall rule ^(may need administrator^)
    )
) else (
    echo WARNING: Please manually allow port 18333 in Windows Firewall
)
echo.

REM Step 7: Start node
echo [Step 7] Starting Retardio node...
echo.

REM Check if already running
tasklist /FI "IMAGENAME eq retardiod.exe" 2>NUL | find /I /N "retardiod.exe">NUL
if !errorlevel! equ 0 (
    echo OK: Retardio node is already running
) else (
    echo Starting node...
    start "Retardio Node" "%RETARDIOD%" -datadir="%DATADIR%"
    echo Waiting for node to start...
    timeout /t 5 /nobreak >nul
    echo OK: Node started
)
echo.

REM Step 8: Create wallet
echo [Step 8] Wallet setup...
echo.

REM Check for existing wallet
"%RETARDIO_CLI%" -datadir="%DATADIR%" listwallets >nul 2>&1
if !errorlevel! neq 0 (
    echo Creating 'mining' wallet...
    "%RETARDIO_CLI%" -datadir="%DATADIR%" createwallet "mining"
    if !errorlevel! equ 0 (
        echo OK: Wallet created
    ) else (
        echo WARNING: Failed to create wallet
    )
) else (
    echo OK: Wallet already exists
)

REM Generate mining address
echo Generating mining address...
for /f "delims=" %%i in ('"%RETARDIO_CLI%" -datadir="%DATADIR%" getnewaddress "mining" "legacy" 2^>nul') do set MINING_ADDRESS=%%i

if not "!MINING_ADDRESS!"=="" (
    echo OK: Mining address: !MINING_ADDRESS!
    echo.
    echo IMPORTANT: Save this address!
    echo   !MINING_ADDRESS!
    echo.
    echo !MINING_ADDRESS! > "%DATADIR%\mining_address.txt"
    echo Also saved to: %DATADIR%\mining_address.txt
) else (
    echo WARNING: Could not generate mining address
)
echo.

REM Step 9: Network status
echo [Step 9] Checking network status...
echo.
timeout /t 3 /nobreak >nul

for /f %%i in ('"%RETARDIO_CLI%" -datadir="%DATADIR%" getconnectioncount 2^>nul') do set PEER_COUNT=%%i
for /f %%i in ('"%RETARDIO_CLI%" -datadir="%DATADIR%" getblockcount 2^>nul') do set BLOCK_COUNT=%%i

echo Network Status:
echo   Connected peers: !PEER_COUNT!
echo   Current block: !BLOCK_COUNT!
echo.

if !PEER_COUNT! gtr 0 (
    echo OK: Connected to !PEER_COUNT! peer^(s^)!
) else (
    echo WARNING: No peers connected yet
    echo.
    echo This is normal if:
    echo   - You haven't added any peers to the config
    echo   - Your peer nodes aren't running yet
    echo   - Firewall is blocking connections
    echo.
    echo To add peers later, edit: %CONF_FILE%
)
echo.

REM Step 10: Show IP addresses
echo [Step 10] Your IP addresses ^(share with peers^):
echo.
ipconfig | findstr /i "IPv4"
echo.

REM Summary
echo ================================================
echo   SETUP COMPLETE!
echo ================================================
echo.
echo Your Retardio node is now running!
echo.
echo Important Information:
echo   * Data directory: %DATADIR%
echo   * Config file: %CONF_FILE%
echo   * Mining address: !MINING_ADDRESS!
echo   * RPC Port: 18332
echo   * P2P Port: 18333
echo.
echo Useful Commands:
echo   * Check status:
echo     %RETARDIO_CLI% -datadir=%DATADIR% getblockchaininfo
echo.
echo   * View peers:
echo     %RETARDIO_CLI% -datadir=%DATADIR% getpeerinfo
echo.
echo   * Check balance:
echo     %RETARDIO_CLI% -datadir=%DATADIR% getbalance
echo.
echo   * Mine 10 blocks:
echo     %RETARDIO_CLI% -datadir=%DATADIR% generatetoaddress 10 !MINING_ADDRESS!
echo.
echo   * Stop node:
echo     %RETARDIO_CLI% -datadir=%DATADIR% stop
echo.
echo Next Steps:
echo   1. Share your IP address with peers
echo   2. Wait for peers to connect
echo   3. Mine some blocks to test
echo   4. Set up stratum mining pool
echo.
echo View logs at: %DATADIR%\debug.log
echo.

REM Create shortcut script
echo @echo off > "%SCRIPT_DIR%retardio-cli.bat"
echo "%RETARDIO_CLI%" -datadir="%DATADIR%" %%* >> "%SCRIPT_DIR%retardio-cli.bat"

echo Created shortcut: retardio-cli.bat
echo   You can now use: retardio-cli getblockcount
echo.
echo Setup complete! Happy mining!
echo.
pause
