#!/bin/bash
#
# Retardio Easy Setup Script
# This script automatically configures your node and connects to the network
#

set -e

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Configuration
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BUILD_DIR="${SCRIPT_DIR}/build"
RETARDIOD="${BUILD_DIR}/bin/retardiod"
RETARDIO_CLI="${BUILD_DIR}/bin/retardio-cli"
DATADIR="${HOME}/.retardio"
CONF_FILE="${DATADIR}/retardio.conf"

# Banner
clear
echo -e "${BOLD}${BLUE}"
echo "╔════════════════════════════════════════════╗"
echo "║                                            ║"
echo "║      RETARDIO EASY SETUP WIZARD            ║"
echo "║                                            ║"
echo "║  This will automatically:                  ║"
echo "║  • Rebuild your node (if needed)          ║"
echo "║  • Configure your node                     ║"
echo "║  • Connect to peer nodes                   ║"
echo "║  • Start your node                         ║"
echo "║                                            ║"
echo "╚════════════════════════════════════════════╝"
echo -e "${NC}"
echo ""

# Function to print step
print_step() {
    echo -e "${BOLD}${BLUE}==>${NC} ${BOLD}$1${NC}"
}

# Function to print success
print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

# Function to print error
print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Function to print warning
print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

# Check if running from correct directory
print_step "Checking environment..."

if [ ! -d "${SCRIPT_DIR}/src" ]; then
    print_error "Please run this script from the retardio-coin directory!"
    exit 1
fi

if [ ! -f "${SCRIPT_DIR}/src/chainparamsseeds.h" ]; then
    print_error "Cannot find chainparamsseeds.h!"
    exit 1
fi

print_success "Environment OK"
echo ""

# Step 1: Check if rebuild is needed
print_step "Step 1: Checking if rebuild is needed..."

NEEDS_REBUILD=0

# Check if binaries exist
if [ ! -f "$RETARDIOD" ] || [ ! -f "$RETARDIO_CLI" ]; then
    print_warning "Binaries not found. Rebuild required."
    NEEDS_REBUILD=1
else
    # Check if chainparamsseeds.h is newer than binary
    if [ "${SCRIPT_DIR}/src/chainparamsseeds.h" -nt "$RETARDIOD" ]; then
        print_warning "chainparamsseeds.h was updated. Rebuild required."
        NEEDS_REBUILD=1
    else
        print_success "Binaries are up to date"
    fi
fi

echo ""

# Step 2: Rebuild if needed
if [ $NEEDS_REBUILD -eq 1 ]; then
    print_step "Step 2: Building Retardio (this may take 5-15 minutes)..."
    echo ""

    # Check if build directory exists
    if [ ! -d "$BUILD_DIR" ]; then
        print_warning "Build directory not found. Creating..."
        mkdir -p "$BUILD_DIR"
        cd "$BUILD_DIR"

        print_warning "Configuring build with CMake..."
        if cmake .. -DBUILD_GUI=OFF 2>&1 | grep -i error; then
            print_error "CMake configuration failed!"
            exit 1
        fi
    else
        cd "$BUILD_DIR"
    fi

    # Build
    print_warning "Compiling (this is the slow part)..."
    if make -j$(nproc) 2>&1 | tee build.log | tail -20; then
        print_success "Build completed successfully!"
    else
        print_error "Build failed! Check ${BUILD_DIR}/build.log for details."
        exit 1
    fi

    cd "$SCRIPT_DIR"
    echo ""
else
    print_step "Step 2: Build not needed (skipping)"
    echo ""
fi

# Step 3: Create data directory
print_step "Step 3: Setting up data directory..."

if [ ! -d "$DATADIR" ]; then
    mkdir -p "$DATADIR"
    print_success "Created $DATADIR"
else
    print_success "Data directory exists"
fi

echo ""

# Step 4: Configure retardio.conf
print_step "Step 4: Configuring retardio.conf..."

if [ -f "$CONF_FILE" ]; then
    print_warning "Configuration file already exists at:"
    echo "  $CONF_FILE"
    read -p "Overwrite it? (y/N): " -n 1 -r
    echo ""
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        print_warning "Keeping existing configuration"
    else
        rm "$CONF_FILE"
        print_warning "Removed old configuration"
    fi
fi

if [ ! -f "$CONF_FILE" ]; then
    print_warning "Creating new configuration file..."

    # Generate random RPC password
    RPC_PASSWORD=$(openssl rand -base64 32 2>/dev/null || cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)

    cat > "$CONF_FILE" << EOF
# Retardio Node Configuration
# Auto-generated by easy_setup.sh on $(date)

# Network Settings
server=1
listen=1
port=18333
maxconnections=125

# RPC Settings
rpcport=18332
rpcuser=retardiouser
rpcpassword=${RPC_PASSWORD}
rpcbind=127.0.0.1
rpcallowip=127.0.0.1

# Performance
dbcache=450
maxmempool=300

# Indexing
txindex=1

# Logging
debug=0

# Peer nodes (will be added below if you provide them)
EOF

    print_success "Configuration file created"
    echo -e "${YELLOW}  RPC Password: ${RPC_PASSWORD}${NC}"
    echo -e "${YELLOW}  (saved to ${CONF_FILE})${NC}"
else
    print_success "Using existing configuration"
fi

echo ""

# Step 5: Add peer nodes
print_step "Step 5: Configure peer nodes..."
echo ""
echo "To connect to the Retardio network, you need to add at least one peer node."
echo ""
read -p "Do you have a peer node IP address to add? (y/N): " -n 1 -r
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    while true; do
        read -p "Enter peer IP address (or 'done' to finish): " peer_ip

        if [ "$peer_ip" = "done" ]; then
            break
        fi

        read -p "Enter peer port (default 18333): " peer_port
        peer_port=${peer_port:-18333}

        # Add to config file
        echo "addnode=${peer_ip}:${peer_port}" >> "$CONF_FILE"
        print_success "Added peer: ${peer_ip}:${peer_port}"

        read -p "Add another peer? (y/N): " -n 1 -r
        echo ""
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            break
        fi
    done
else
    print_warning "No peers added. You can add them later by editing:"
    echo "  $CONF_FILE"
    echo ""
    echo "Add lines like: addnode=192.168.1.100:18333"
fi

echo ""

# Step 6: Firewall check
print_step "Step 6: Firewall configuration..."
echo ""
echo "Port 18333 must be open for incoming connections."
echo ""

if command -v ufw &> /dev/null; then
    if sudo ufw status | grep -q "18333.*ALLOW"; then
        print_success "Port 18333 is already allowed in UFW"
    else
        read -p "Allow port 18333 in UFW firewall? (y/N): " -n 1 -r
        echo ""
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            sudo ufw allow 18333/tcp
            print_success "Port 18333 allowed in UFW"
        else
            print_warning "You'll need to manually allow port 18333"
        fi
    fi
else
    print_warning "UFW not detected. Please manually configure your firewall to allow port 18333/tcp"
fi

echo ""

# Step 7: Create or verify wallet
print_step "Step 7: Wallet setup..."
echo ""

# Check if node is already running
if pgrep -x "retardiod" > /dev/null; then
    print_warning "Retardio node is already running"
    NODE_WAS_RUNNING=1
else
    NODE_WAS_RUNNING=0
    print_warning "Starting node to create wallet..."
    "$RETARDIOD" -datadir="$DATADIR" -daemon
    sleep 5
fi

# Check for existing wallets
WALLET_LIST=$("$RETARDIO_CLI" -datadir="$DATADIR" listwallets 2>/dev/null || echo "")

if [ -z "$WALLET_LIST" ] || [ "$WALLET_LIST" = "[]" ]; then
    print_warning "No wallet found. Creating 'mining' wallet..."
    if "$RETARDIO_CLI" -datadir="$DATADIR" createwallet "mining" 2>&1; then
        print_success "Wallet 'mining' created"
    else
        print_error "Failed to create wallet"
    fi
else
    print_success "Wallet already exists"
fi

# Generate mining address
print_warning "Generating mining address..."
MINING_ADDRESS=$("$RETARDIO_CLI" -datadir="$DATADIR" getnewaddress "mining" "legacy" 2>/dev/null || echo "")

if [ -n "$MINING_ADDRESS" ]; then
    print_success "Mining address: ${MINING_ADDRESS}"
    echo ""
    echo -e "${YELLOW}IMPORTANT: Save this address!${NC}"
    echo "  $MINING_ADDRESS"
    echo ""

    # Save to file
    echo "$MINING_ADDRESS" > "${DATADIR}/mining_address.txt"
    echo -e "Also saved to: ${DATADIR}/mining_address.txt"
else
    print_warning "Could not generate mining address (will need to do manually)"
fi

echo ""

# Step 8: Display network info
print_step "Step 8: Checking network status..."
echo ""

# Wait a moment for connections to establish
sleep 3

PEER_COUNT=$("$RETARDIO_CLI" -datadir="$DATADIR" getconnectioncount 2>/dev/null || echo "0")
BLOCK_COUNT=$("$RETARDIO_CLI" -datadir="$DATADIR" getblockcount 2>/dev/null || echo "0")

echo -e "${BOLD}Network Status:${NC}"
echo "  Connected peers: $PEER_COUNT"
echo "  Current block: $BLOCK_COUNT"
echo ""

if [ "$PEER_COUNT" -gt 0 ]; then
    print_success "Connected to $PEER_COUNT peer(s)!"
    echo ""
    echo -e "${BOLD}Peer details:${NC}"
    "$RETARDIO_CLI" -datadir="$DATADIR" getpeerinfo | grep -E '"addr"|"version"|"subver"' | head -15
else
    print_warning "No peers connected yet."
    echo ""
    echo "This is normal if:"
    echo "  • You haven't added any peers to the config"
    echo "  • Your peer nodes aren't running yet"
    echo "  • Firewall is blocking connections"
    echo ""
    echo "To add peers later, edit: $CONF_FILE"
    echo "Add lines like: addnode=192.168.1.100:18333"
fi

echo ""

# Get local IP addresses
print_step "Your IP addresses (share these with peers):"
echo ""

if command -v ip &> /dev/null; then
    echo -e "${BOLD}Local IPs:${NC}"
    ip addr show | grep "inet " | grep -v "127.0.0.1" | awk '{print "  " $2}' | sed 's/\/.*//'
elif command -v ifconfig &> /dev/null; then
    echo -e "${BOLD}Local IPs:${NC}"
    ifconfig | grep "inet " | grep -v "127.0.0.1" | awk '{print "  " $2}'
fi

# Get public IP
if command -v curl &> /dev/null; then
    PUBLIC_IP=$(curl -s ifconfig.me 2>/dev/null || echo "Unable to detect")
    echo ""
    echo -e "${BOLD}Public IP:${NC}"
    echo "  $PUBLIC_IP"
fi

echo ""

# Step 9: Summary and next steps
print_step "Setup Complete! 🎉"
echo ""
echo -e "${GREEN}${BOLD}Your Retardio node is now running!${NC}"
echo ""
echo -e "${BOLD}Important Information:${NC}"
echo "  • Data directory: $DATADIR"
echo "  • Config file: $CONF_FILE"
echo "  • Mining address: $MINING_ADDRESS"
echo "  • RPC Port: 18332"
echo "  • P2P Port: 18333"
echo ""
echo -e "${BOLD}Useful Commands:${NC}"
echo "  • Check status:      $RETARDIO_CLI -datadir=$DATADIR getblockchaininfo"
echo "  • View peers:        $RETARDIO_CLI -datadir=$DATADIR getpeerinfo"
echo "  • Check balance:     $RETARDIO_CLI -datadir=$DATADIR getbalance"
echo "  • Mine blocks:       $RETARDIO_CLI -datadir=$DATADIR generatetoaddress 10 $MINING_ADDRESS"
echo "  • Stop node:         $RETARDIO_CLI -datadir=$DATADIR stop"
echo ""
echo -e "${BOLD}Next Steps:${NC}"
echo "  1. Share your IP address with peers so they can connect to you"
echo "  2. Wait for peers to connect (or add more in $CONF_FILE)"
echo "  3. Mine some blocks to test: $RETARDIO_CLI -datadir=$DATADIR generatetoaddress 10 $MINING_ADDRESS"
echo "  4. Set up a stratum mining pool once network is stable"
echo ""
echo -e "${BOLD}View logs:${NC}"
echo "  tail -f $DATADIR/debug.log"
echo ""
echo -e "${YELLOW}Remember: All peers must be using the same genesis block and network!${NC}"
echo ""

# Create quick access script
cat > "${SCRIPT_DIR}/retardio-cli.sh" << 'EOFCLI'
#!/bin/bash
# Quick access to retardio-cli
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
"${SCRIPT_DIR}/build/bin/retardio-cli" -datadir="${HOME}/.retardio" "$@"
EOFCLI

chmod +x "${SCRIPT_DIR}/retardio-cli.sh"

echo -e "${GREEN}Created shortcut: ./retardio-cli.sh${NC}"
echo "  You can now use: ./retardio-cli.sh getblockcount"
echo ""
echo -e "${BOLD}${GREEN}Setup complete! Happy mining! 🚀${NC}"
