#!/bin/bash
#
# Retardio Node Setup Script for Raspberry Pi 5
# Optimized for 4GB RAM model
#

set -e

echo "================================================"
echo "  Retardio Node Setup for Raspberry Pi 5 (4GB)"
echo "================================================"
echo ""

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Get current user
CURRENT_USER=$(whoami)
HOME_DIR=$(eval echo ~$CURRENT_USER)
DATA_DIR="$HOME_DIR/.retardio"

# Check if running on ARM64
ARCH=$(uname -m)
if [[ "$ARCH" != "aarch64" ]]; then
    echo -e "${YELLOW}Warning: This script is optimized for ARM64 (aarch64).${NC}"
    echo -e "${YELLOW}Detected architecture: $ARCH${NC}"
    read -p "Continue anyway? (y/N) " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# Check RAM
TOTAL_RAM=$(free -m | awk '/^Mem:/{print $2}')
echo -e "${GREEN}Detected RAM: ${TOTAL_RAM}MB${NC}"

if [[ $TOTAL_RAM -lt 3500 ]]; then
    echo -e "${YELLOW}Warning: Less than 4GB RAM detected. Performance may be limited.${NC}"
fi

echo ""
echo "Step 1/7: Updating system..."
sudo apt update && sudo apt upgrade -y

echo ""
echo "Step 2/7: Installing dependencies..."
sudo apt install -y \
    build-essential libtool autotools-dev automake pkg-config \
    libssl-dev libevent-dev bsdmainutils python3 \
    libboost-all-dev libsqlite3-dev libminiupnpc-dev \
    libnatpmp-dev cmake ninja-build git

echo ""
echo "Step 3/7: Cloning Retardio repository..."
cd "$HOME_DIR"
if [ -d "retardio" ]; then
    echo "Repository already exists, updating..."
    cd retardio
    git pull origin 29.x-knots
else
    git clone https://github.com/hydden682/retardio.git -b 29.x-knots
    cd retardio
fi

echo ""
echo "Step 4/7: Building Retardio (this may take 30-60 minutes)..."
mkdir -p build
cd build

# Configure with optimizations for RPi5
cmake -G Ninja .. \
    -DBUILD_GUI=OFF \
    -DWITH_ZMQ=OFF \
    -DENABLE_WALLET=ON \
    -DCMAKE_BUILD_TYPE=Release

# Build with 2 jobs to avoid OOM on 4GB
ninja -j2

echo ""
echo "Step 5/7: Installing..."
sudo ninja install

echo ""
echo "Step 6/7: Creating configuration..."
mkdir -p "$DATA_DIR"

# Generate random RPC password
RPC_PASSWORD=$(openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32)

cat > "$DATA_DIR/retardio.conf" << EOF
# Retardio Node Configuration
# Generated by setup_rpi5.sh on $(date)

# Network
chain=regtest

# RPC Settings
server=1
rpcuser=retardiorpc
rpcpassword=$RPC_PASSWORD
rpcallowip=127.0.0.1
rpcport=22555

# Performance (optimized for 4GB RAM)
dbcache=512
maxmempool=100
maxconnections=40

# Network
listen=1
port=22556

# Logging
debug=0
printtoconsole=0
EOF

echo -e "${GREEN}RPC Password saved to: $DATA_DIR/retardio.conf${NC}"
echo -e "${YELLOW}Your RPC password is: $RPC_PASSWORD${NC}"
echo -e "${YELLOW}Please save this password securely!${NC}"

echo ""
echo "Step 7/7: Creating systemd service..."
sudo tee /etc/systemd/system/retardiod.service > /dev/null << EOF
[Unit]
Description=Retardio Daemon
After=network.target

[Service]
Type=forking
User=$CURRENT_USER
ExecStart=/usr/local/bin/retardiod -daemon -conf=$DATA_DIR/retardio.conf -datadir=$DATA_DIR
ExecStop=/usr/local/bin/retardio-cli -conf=$DATA_DIR/retardio.conf stop
Restart=on-failure
RestartSec=30
TimeoutStopSec=300
LimitNOFILE=65535

[Install]
WantedBy=multi-user.target
EOF

sudo systemctl daemon-reload
sudo systemctl enable retardiod

echo ""
echo "================================================"
echo -e "${GREEN}  Installation Complete!${NC}"
echo "================================================"
echo ""
echo "Start the node:"
echo "  sudo systemctl start retardiod"
echo ""
echo "Check status:"
echo "  sudo systemctl status retardiod"
echo "  retardio-cli getblockchaininfo"
echo ""
echo "View logs:"
echo "  sudo journalctl -u retardiod -f"
echo ""
echo "Configuration file:"
echo "  $DATA_DIR/retardio.conf"
echo ""
echo "Data directory:"
echo "  $DATA_DIR"
echo ""
echo -e "${YELLOW}Remember to save your RPC password!${NC}"
echo ""

# Ask to start now
read -p "Start the node now? (Y/n) " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]] || [[ -z $REPLY ]]; then
    sudo systemctl start retardiod
    echo ""
    echo "Node started! Checking status..."
    sleep 3
    retardio-cli getblockchaininfo 2>/dev/null || echo "Node is starting up, please wait..."
fi

echo ""
echo "Done! Your Retardio node is ready."
